version: '3.8'

services:
  challenge-registry-api-db:
    image: sagebionetworks/challenge-registry-api-db:latest
    container_name: challenge-registry-api-db
    restart: always
    env_file:
      - ./apps/api-db/.env
    networks:
      - challenge-registry
    ports:
      - "27017:27017"
    volumes:
      - challenge-registry-api-db:/data/db

  challenge-registry-api:
    image: sagebionetworks/challenge-registry-api:latest
    container_name: challenge-registry-api
    restart: always
    env_file:
      - ./apps/api/.env
    environment:
      - DB_DOMAIN=challenge-registry-api-db
    networks:
      - challenge-registry
    ports:
      - "8080:8080"
    depends_on:
      - challenge-registry-api-db

  challenge-registry-web-app:
    image: sagebionetworks/challenge-registry-web-app:latest
    container_name: challenge-registry-web-app
    restart: always
    env_file:
      - ./apps/web-app/.env
    environment:
      - SERVICE_HOST=challenge-registry-api
      - SERVICE_PORT=8080
    networks:
      - challenge-registry
    ports:
      - "80:80"
    depends_on:
      - challenge-registry-api
      - challenge-registry-movie-api
      - keycloak

  challenge-registry-movie-api:
    image: sagebionetworks/challenge-registry-movie-api:latest
    container_name: challenge-registry-movie-api
    restart: always
    env_file:
      - ./apps/movie-api/.env
    networks:
      - challenge-registry
    ports:
      - "9000:9000"

  keycloak:
    image: sagebionetworks/keycloak:latest
    container_name: keycloak
    restart: always
    env_file:
      - ./apps/keycloak/.env
    volumes:
      - ./apps/keycloak/data/h2:/opt/keycloak/data/h2
    networks:
      - challenge-registry
    ports:
      - "8081:8080"
    command: start-dev
    depends_on:
      - keycloak-db
      - challenge-registry-movie-api  # cheating temporarily to make it easier to start the stack.

  keycloak-db:
    image: sagebionetworks/keycloak-db:latest
    container_name: keycloak-db
    restart: always
    env_file:
      - ./apps/keycloak-db/.env
    volumes:
      - keycloak-db:/var/lib/postgresql/data
      - ./apps/keycloak-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - challenge-registry
    ports:
      - "5432:5432"

networks:
  challenge-registry:

volumes:
  challenge-registry-api-db:
    name: challenge-registry-api-db
  keycloak-db:
    name: keycloak-db